#61 Session header authentication
IncQueryLabs/incquery-server-jupyter pull request #63
Opened 2021-10-12 11:49 UTC by banko-marton

Fixes #61 

Added ability to connect to IQS instance with authentication header (name & value).
Extended IQS Connection Widget with multiple auth options.

2021-10-13 07:18 UTC, FuzesiMate approved these changes

2021-10-15 14:10 UTC, bergmanngabor requested changes

2021-10-15 14:10 UTC, bergmanngabor commented on source/incqueryserver-jupyter/iqs_jupyter/config_defaults.py
> +default_use_auth_header: bool = False
These 3 should be modified to use the `default_IQS_` prefix - after all, they relate to the connection to the IQS, as opposed to e.g. MMS. (probably we can keep the old names in deprecated form, to retain compatibility, and use their value if the newer environment variable name is not present)

Sorry for not catching this in earlier reviews.

2021-10-15 14:10 UTC, bergmanngabor commented on source/incqueryserver-jupyter/iqs_jupyter/authentication.py
> +                      self.auth_header_checkbox, self.auth_header_name_field, self.auth_header_value_field]
why are these in the `ask_for_user_pw` branch? I though we do not ask for user/pass when we ask for auth header fields; also, should we not branch on the value of `self.auth_header_checkbox` to determine whether we should display these fields?

2021-10-15 14:10 UTC, bergmanngabor commented on source/incqueryserver-jupyter/iqs_jupyter/authentication.py
>          if ask_for_user_pw:
??? if there is a `ask_for_user_pw_checkbox` why do you use its (possibly obsolete) initial value, as opposed to its actual value? will the set of displayed widgets change if I check/uncheck the checkbox? 

Same with `auth_header_checkbox`

2021-10-21 08:48 UTC, pappist approved these changes

2021-10-21 09:51 UTC, merged